main: org.hydev.mcpm.SpigotEntry
name: MCPM
version: '@version@'
description: Minecraft Package Manager for Bukkit/Spiget Servers
api-version: 1.18
authors: [Hykilpikonna, 1whatleytay, MstrPikachu, kchprog, jerryzhu509, thudoan1706,
  aanushkasharma]
website: https://github.com/CSC207-2022F-UofT/mcpm
commands:
  mcpm:
    description: Minecraft package manager
    usage: 'View help: /mcpm -h'
    permission: mcpm.use
libraries:
- net.sourceforge.argparse4j:argparse4j:0.9.0
- org.apache.httpcomponents.client5:httpclient5-fluent:5.2-beta1
- com.fasterxml.jackson.core:jackson-core:2.14.0
- com.fasterxml.jackson.dataformat:jackson-dataformat-yaml:2.14.0
- com.google.guava:guava:31.1-jre
- org.jetbrains:annotations:23.0.0
- org.fusesource.jansi:jansi:2.4.0
- org.apache.commons:commons-lang3:3.12.0
- com.github.luben:zstd-jni:1.5.2-5
- io.airlift:aircompressor:0.21
