main: org.hydev.mcpm.SpigotEntry
name: MCPM
version: @version@
description: Minecraft Package Manager for Bukkit/Spiget Servers
api-version: 1.18
authors: [Hykilpikonna, 1whatleytay, MstrPikachu, kchprog, jerryzhu509, thudoan1706, aanushkasharma]
website: https://github.com/CSC207-2022F-UofT/mcpm
