version: "3.8"

services:
  mcprs-sync:
    container_name: mcprs-sync
    build: sync
    volumes:
      - /data/mcprs:/data:z
    environment:
      - RSYNC_SOURCE=rsync://mcprs-bell.hydev.org/mcprs
      - RSYNC_INTERVAL=24
    restart: always

  mcprs-nginx:
    container_name: mcprs-nginx
    build: nginx
    volumes:
      - /data/mcprs:/data:z
    ports:
      - "80:80"
    restart: always

  mcprs-rsyncd:
    container_name: mcprs-rsyncd
    image: axiom/rsync-server
    ports:
      - "873:873"
    volumes:
      - /data/mcprs:/data:z
    restart: always
