name: Gradle Publish

on:
  release:
    types: [created]

permissions:
  checks: write
  actions: read
  contents: read

jobs:
  build:
    name: Gradle Test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up Java JDK
        uses: actions/setup-java@v3
        with:
          java-version: '19'
          distribution: 'adopt'

      - name: Gradle Wrapper Validation
        uses: gradle/wrapper-validation-action@v1

      - name: Setup Gradle with Dependency Cache
        uses: gradle/gradle-build-action@v2.3.3

      - name: Gradle Build
        run: ./gradlew build --scan

      - name: Gradle Test
        run: ./gradlew test

      - name: Publish Artifacts
        uses: actions/upload-artifact@v3
        with:
          name: mcpm
          path: build/libs

      - name: Publish Maven Package to Github Package Registry
        run: ./gradlew publish
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}


